# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          java-version: 11
      - name: Download Scantist-Bom-Detect
        run: curl -s https://download.scantist.io/sca-bom-detect-v4.jar --output sca-bom-detect-v4.jar
        
      - name: Upload to Scantist 
        env: # Setting the Token
          SCANTISTTOKEN: ${{secrets.SCANTISTTOKEN}}
          SCANTIST_IMPORT_URL : "https://api-v4dev.scantist.io/v2/scans/ci-scan/" # add this line if you are setting up on a dedicated scantist server
        run: java -jar sca-bom-detect-v4.jar --debug
